### ISSUE TITLE
Correct font not showing up on Mac

### ISSUE THREAD

**Issue by pursellce** [pursellce/pursellce.github.io#2]
Custom font not loading on Macs and other non-Windows devices.

![Before Custom Font Fix](https://user-images.githubusercontent.com/114625211/198514991-719a01c3-89b2-46de-86a0-c4d337db816e.jpg)

**Comment by CamronVZ** [comment]
Fixed our custom font not showing up on non-Windows devices. It now loads the proper font on all devices as shown in this screenshot.

![After Custom Font Fix](https://user-images.githubusercontent.com/114625211/198515091-7fc8db99-9cf6-4141-8482-67d412ba9c96.jpg)
